version: '3.8'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: employee-management-app:latest
    container_name: employee-management-app
    ports:
      - "8080:80"
